@endpoint = https://h87mdl5epj.execute-api.eu-west-1.amazonaws.com/prod/

GET {{endpoint}}/spaces
###

GET {{endpoint}}/spaces?spaceId=fdaa11fc-abd8-47b3-9fd5-6730329ba945
###

GET {{endpoint}}/spaces?location=London
###

POST {{endpoint}}/spaces
Content-Type: application/json

{
  "location": "London",
  "name": "Best location"
}
###

PUT {{endpoint}}/spaces?spaceId=97f6edbe-beac-4ca9-a9d2-16411491463a
Content-Type: application/json

{
  "location": "London again"
}
###

DELETE {{endpoint}}/spaces?spaceId=fdaa11fc-abd8-47b3-9fd5-6730329ba945
###


