@endpoint = https://h87mdl5epj.execute-api.eu-west-1.amazonaws.com/prod/

GET {{endpoint}}/spaces
###

GET {{endpoint}}/spaces?spaceId=7ab8194b-5def-414d-b0fa-e8449bc9949f
###

GET {{endpoint}}/spaces?location=London
###

POST {{endpoint}}/spaces
Content-Type: application/json

{
  "location": "London",
  "name": "Best location"
}
###

PUT {{endpoint}}/spaces?spaceId=7ab8194b-5def-414d-b0fa-e8449bc9949f
Content-Type: application/json

{
  "location": "Harrogate"
}
###

DELETE {{endpoint}}/spaces?spaceId=fdaa11fc-abd8-47b3-9fd5-6730329ba945
###


